### ISSUE TITLE
Cells with single quote to escape equal sign

### ISSUE THREAD

**Issue by done712** [vinci1it2000/formulas#60]
Package cannot handle cells in which a single quote is used to escape an equal sign at the beginning of the cell, i.e. in my excel file there is a cell with content "'= this is a test" (please note single quote at the beginning of the string) which raises the error "formulas.errors.FormulaError: ('Not a valid formula:\n%s', '= this is a test')".

**Comment by vinci1it2000** [comment]
This has been fixed with 844dbf84.

**Comment by owinebar** [comment]
This is still an issue when exporting a workbook as a dictionary.  The single quote escape is not in the exported vale, so when the dictionary is reloaded it's interpreted as a formula.
